apiVersion: v1
kind: Secret

metadata:
  name: mysql-secret

type: Opaque

stringData:
  MYSQL_ROOT_PASSWORD: aryan2004
  MYSQL_DB_URL: mysql+pymysql://root:aryan2004@mysql-service:3306/ticket_booking